//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace TriagePic.gov.nih.nlm.hepldemo {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name=" Web ServicesBinding", Namespace="http://localhost/pls")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Basic))]
    public partial class WebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback shn_pls_get_incident_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback shn_pls_create_uuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback shn_pls_create_uuid_batchOperationCompleted;
        
        private System.Threading.SendOrPostCallback shn_pls_get_person_dataOperationCompleted;
        
        private System.Threading.SendOrPostCallback shn_pls_basic_searchOperationCompleted;
        
        private System.Threading.SendOrPostCallback shn_pls_basic_search_allOperationCompleted;
        
        private System.Threading.SendOrPostCallback shn_pls_testOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServices() {
            this.Url = global::TriagePic.Properties.Settings.Default.TriagePic_gov_nih_nlm_hepldemo__Web_Services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event shn_pls_get_incident_listCompletedEventHandler shn_pls_get_incident_listCompleted;
        
        /// <remarks/>
        public event shn_pls_create_uuidCompletedEventHandler shn_pls_create_uuidCompleted;
        
        /// <remarks/>
        public event shn_pls_create_uuid_batchCompletedEventHandler shn_pls_create_uuid_batchCompleted;
        
        /// <remarks/>
        public event shn_pls_get_person_dataCompletedEventHandler shn_pls_get_person_dataCompleted;
        
        /// <remarks/>
        public event shn_pls_basic_searchCompletedEventHandler shn_pls_basic_searchCompleted;
        
        /// <remarks/>
        public event shn_pls_basic_search_allCompletedEventHandler shn_pls_basic_search_allCompleted;
        
        /// <remarks/>
        public event shn_pls_testCompletedEventHandler shn_pls_testCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/pls#shn_pls_get_incident_list", RequestNamespace="http://localhost/pls", ResponseNamespace="http://localhost/pls")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Basic[] shn_pls_get_incident_list() {
            object[] results = this.Invoke("shn_pls_get_incident_list", new object[0]);
            return ((Basic[])(results[0]));
        }
        
        /// <remarks/>
        public void shn_pls_get_incident_listAsync() {
            this.shn_pls_get_incident_listAsync(null);
        }
        
        /// <remarks/>
        public void shn_pls_get_incident_listAsync(object userState) {
            if ((this.shn_pls_get_incident_listOperationCompleted == null)) {
                this.shn_pls_get_incident_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshn_pls_get_incident_listOperationCompleted);
            }
            this.InvokeAsync("shn_pls_get_incident_list", new object[0], this.shn_pls_get_incident_listOperationCompleted, userState);
        }
        
        private void Onshn_pls_get_incident_listOperationCompleted(object arg) {
            if ((this.shn_pls_get_incident_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shn_pls_get_incident_listCompleted(this, new shn_pls_get_incident_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/pls#shn_pls_create_uuid", RequestNamespace="http://localhost/pls", ResponseNamespace="http://localhost/pls")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Basic[] shn_pls_create_uuid() {
            object[] results = this.Invoke("shn_pls_create_uuid", new object[0]);
            return ((Basic[])(results[0]));
        }
        
        /// <remarks/>
        public void shn_pls_create_uuidAsync() {
            this.shn_pls_create_uuidAsync(null);
        }
        
        /// <remarks/>
        public void shn_pls_create_uuidAsync(object userState) {
            if ((this.shn_pls_create_uuidOperationCompleted == null)) {
                this.shn_pls_create_uuidOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshn_pls_create_uuidOperationCompleted);
            }
            this.InvokeAsync("shn_pls_create_uuid", new object[0], this.shn_pls_create_uuidOperationCompleted, userState);
        }
        
        private void Onshn_pls_create_uuidOperationCompleted(object arg) {
            if ((this.shn_pls_create_uuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shn_pls_create_uuidCompleted(this, new shn_pls_create_uuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/pls#shn_pls_create_uuid_batch", RequestNamespace="http://localhost/pls", ResponseNamespace="http://localhost/pls")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Basic[] shn_pls_create_uuid_batch() {
            object[] results = this.Invoke("shn_pls_create_uuid_batch", new object[0]);
            return ((Basic[])(results[0]));
        }
        
        /// <remarks/>
        public void shn_pls_create_uuid_batchAsync() {
            this.shn_pls_create_uuid_batchAsync(null);
        }
        
        /// <remarks/>
        public void shn_pls_create_uuid_batchAsync(object userState) {
            if ((this.shn_pls_create_uuid_batchOperationCompleted == null)) {
                this.shn_pls_create_uuid_batchOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshn_pls_create_uuid_batchOperationCompleted);
            }
            this.InvokeAsync("shn_pls_create_uuid_batch", new object[0], this.shn_pls_create_uuid_batchOperationCompleted, userState);
        }
        
        private void Onshn_pls_create_uuid_batchOperationCompleted(object arg) {
            if ((this.shn_pls_create_uuid_batchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shn_pls_create_uuid_batchCompleted(this, new shn_pls_create_uuid_batchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/pls#shn_pls_get_person_data", RequestNamespace="http://localhost/pls", ResponseNamespace="http://localhost/pls")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Basic[] shn_pls_get_person_data() {
            object[] results = this.Invoke("shn_pls_get_person_data", new object[0]);
            return ((Basic[])(results[0]));
        }
        
        /// <remarks/>
        public void shn_pls_get_person_dataAsync() {
            this.shn_pls_get_person_dataAsync(null);
        }
        
        /// <remarks/>
        public void shn_pls_get_person_dataAsync(object userState) {
            if ((this.shn_pls_get_person_dataOperationCompleted == null)) {
                this.shn_pls_get_person_dataOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshn_pls_get_person_dataOperationCompleted);
            }
            this.InvokeAsync("shn_pls_get_person_data", new object[0], this.shn_pls_get_person_dataOperationCompleted, userState);
        }
        
        private void Onshn_pls_get_person_dataOperationCompleted(object arg) {
            if ((this.shn_pls_get_person_dataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shn_pls_get_person_dataCompleted(this, new shn_pls_get_person_dataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/pls#shn_pls_basic_search", RequestNamespace="http://localhost/pls", ResponseNamespace="http://localhost/pls")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Basic[] shn_pls_basic_search() {
            object[] results = this.Invoke("shn_pls_basic_search", new object[0]);
            return ((Basic[])(results[0]));
        }
        
        /// <remarks/>
        public void shn_pls_basic_searchAsync() {
            this.shn_pls_basic_searchAsync(null);
        }
        
        /// <remarks/>
        public void shn_pls_basic_searchAsync(object userState) {
            if ((this.shn_pls_basic_searchOperationCompleted == null)) {
                this.shn_pls_basic_searchOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshn_pls_basic_searchOperationCompleted);
            }
            this.InvokeAsync("shn_pls_basic_search", new object[0], this.shn_pls_basic_searchOperationCompleted, userState);
        }
        
        private void Onshn_pls_basic_searchOperationCompleted(object arg) {
            if ((this.shn_pls_basic_searchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shn_pls_basic_searchCompleted(this, new shn_pls_basic_searchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/pls#shn_pls_basic_search_all", RequestNamespace="http://localhost/pls", ResponseNamespace="http://localhost/pls")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Basic[] shn_pls_basic_search_all() {
            object[] results = this.Invoke("shn_pls_basic_search_all", new object[0]);
            return ((Basic[])(results[0]));
        }
        
        /// <remarks/>
        public void shn_pls_basic_search_allAsync() {
            this.shn_pls_basic_search_allAsync(null);
        }
        
        /// <remarks/>
        public void shn_pls_basic_search_allAsync(object userState) {
            if ((this.shn_pls_basic_search_allOperationCompleted == null)) {
                this.shn_pls_basic_search_allOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshn_pls_basic_search_allOperationCompleted);
            }
            this.InvokeAsync("shn_pls_basic_search_all", new object[0], this.shn_pls_basic_search_allOperationCompleted, userState);
        }
        
        private void Onshn_pls_basic_search_allOperationCompleted(object arg) {
            if ((this.shn_pls_basic_search_allCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shn_pls_basic_search_allCompleted(this, new shn_pls_basic_search_allCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/pls#shn_pls_test", RequestNamespace="http://localhost/pls", ResponseNamespace="http://localhost/pls")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Basic[] shn_pls_test() {
            object[] results = this.Invoke("shn_pls_test", new object[0]);
            return ((Basic[])(results[0]));
        }
        
        /// <remarks/>
        public void shn_pls_testAsync() {
            this.shn_pls_testAsync(null);
        }
        
        /// <remarks/>
        public void shn_pls_testAsync(object userState) {
            if ((this.shn_pls_testOperationCompleted == null)) {
                this.shn_pls_testOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshn_pls_testOperationCompleted);
            }
            this.InvokeAsync("shn_pls_test", new object[0], this.shn_pls_testOperationCompleted, userState);
        }
        
        private void Onshn_pls_testOperationCompleted(object arg) {
            if ((this.shn_pls_testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shn_pls_testCompleted(this, new shn_pls_testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost/pls")]
    public partial class Basic {
        
        private string nameField;
        
        private string idField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void shn_pls_get_incident_listCompletedEventHandler(object sender, shn_pls_get_incident_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shn_pls_get_incident_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shn_pls_get_incident_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Basic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Basic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void shn_pls_create_uuidCompletedEventHandler(object sender, shn_pls_create_uuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shn_pls_create_uuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shn_pls_create_uuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Basic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Basic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void shn_pls_create_uuid_batchCompletedEventHandler(object sender, shn_pls_create_uuid_batchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shn_pls_create_uuid_batchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shn_pls_create_uuid_batchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Basic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Basic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void shn_pls_get_person_dataCompletedEventHandler(object sender, shn_pls_get_person_dataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shn_pls_get_person_dataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shn_pls_get_person_dataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Basic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Basic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void shn_pls_basic_searchCompletedEventHandler(object sender, shn_pls_basic_searchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shn_pls_basic_searchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shn_pls_basic_searchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Basic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Basic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void shn_pls_basic_search_allCompletedEventHandler(object sender, shn_pls_basic_search_allCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shn_pls_basic_search_allCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shn_pls_basic_search_allCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Basic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Basic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void shn_pls_testCompletedEventHandler(object sender, shn_pls_testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shn_pls_testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shn_pls_testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Basic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Basic[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591